#
# Makefile for the Cypress touchkey driver
#

obj-$(CONFIG_KEYBOARD_CYPRESS_SAMMY_CM9) += cypress-touchkey-sammy-cm9.o issp_driver_routines.o issp_main.o issp_routines.o
obj-$(CONFIG_KEYBOARD_CYPRESS_AOKP) += cypress-touchkey-aokp.o issp_driver_routines.o issp_main.o issp_routines.o
